version: 2
updates:
  # Package updates for root monorepo workspace
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 10

  # Package updates for frontend directory
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 10
