version: '1.0'

services:
  fastapi:
    build: .
    container_name: fastAPi-container
    ports:
      - "8080:8080"

    env_file:
      - .env
    volumes:
      - .:/app

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app:/app/fastAPI

    restart: always
    