"""refactor_collaborators_to_many_to_many

Revision ID: 16b1122def47
Revises: aa01d048ea25
Create Date: 2026-05-19 07:39:39.255142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b1122def47'
down_revision: Union[str, Sequence[str], None] = 'aa01d048ea25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_collaborator_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('collab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_collaborator_association_id'), 'repo_collaborator_association', ['id'], unique=False)
    op.add_column('collaborators', sa.Column('github_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('_repo_collaborator_uc'), 'collaborators', type_='unique')
    op.drop_index(op.f('ix_collaborators_collab_id'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_github_id'), 'collaborators', ['github_id'], unique=True)
    op.drop_constraint(op.f('collaborators_repo_id_fkey'), 'collaborators', type_='foreignkey')
    op.drop_column('collaborators', 'collab_id')
    op.drop_column('collaborators', 'repo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborators', sa.Column('repo_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('collaborators', sa.Column('collab_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('collaborators_repo_id_fkey'), 'collaborators', 'repositories', ['repo_id'], ['repo_id'])
    op.drop_index(op.f('ix_collaborators_github_id'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_collab_id'), 'collaborators', ['collab_id'], unique=False)
    op.create_unique_constraint(op.f('_repo_collaborator_uc'), 'collaborators', ['repo_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('collaborators', 'github_id')
    op.drop_index(op.f('ix_repo_collaborator_association_id'), table_name='repo_collaborator_association')
    op.drop_table('repo_collaborator_association')
    # ### end Alembic commands ###
