"""Add unique constraint to collaborator association

Revision ID: 42ef1404e378
Revises: a77ab3d7fe6c
Create Date: 2026-05-19 15:39:28.707021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ef1404e378'
down_revision: Union[str, Sequence[str], None] = 'a77ab3d7fe6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_repository_association_id'), table_name='language_repository_association')
    op.drop_table('language_repository_association')
    op.create_unique_constraint('_repo_collab_uc', 'collaboration_assosiation', ['repo_id', 'collab_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_repo_collab_uc', 'collaboration_assosiation', type_='unique')
    op.create_table('language_repository_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lang_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['languages.id'], name=op.f('language_repository_association_lang_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], name=op.f('language_repository_association_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('language_repository_association_pkey'))
    )
    op.create_index(op.f('ix_language_repository_association_id'), 'language_repository_association', ['id'], unique=False)
    # ### end Alembic commands ###
