""" ADD Flags for secret repositories.

Revision ID: 565ab48ad281
Revises: 79b55ab3ed7f
Create Date: 2026-03-19 20:04:28.487625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565ab48ad281'
down_revision: Union[str, Sequence[str], None] = '79b55ab3ed7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_secret', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_secret')
    # ### end Alembic commands ###
