"""remove parent_owner from RepositoryModel

Revision ID: 56f2011a9e50
Revises: bdb0bc14aa04
Create Date: 2026-06-03 11:02:30.064580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f2011a9e50'
down_revision: Union[str, Sequence[str], None] = 'bdb0bc14aa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'parent_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('parent_owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
