""" RENAME rename last_updated -> last_check.

Revision ID: 5938e92cbce1
Revises: 565ab48ad281
Create Date: 2026-03-19 20:30:11.301772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5938e92cbce1'
down_revision: Union[str, Sequence[str], None] = '565ab48ad281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_check', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('repositories', 'last_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('repositories', 'last_check')
    # ### end Alembic commands ###
