"""remove_unique_constraints_from_collaborators

Revision ID: 6e62a9dc8243
Revises: 870ae6609935
Create Date: 2026-05-18 22:00:38.606115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e62a9dc8243'
down_revision: Union[str, Sequence[str], None] = '870ae6609935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborators', sa.Column('profile_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_collaborators_collab_id'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_collab_id'), 'collaborators', ['collab_id'], unique=False)
    op.drop_index(op.f('ix_collaborators_name'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_name'), 'collaborators', ['name'], unique=False)
    op.alter_column('language_repository_association', 'repo_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('repositories', sa.Column('owner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'owner_url')
    op.alter_column('language_repository_association', 'repo_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_collaborators_name'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_name'), 'collaborators', ['name'], unique=True)
    op.drop_index(op.f('ix_collaborators_collab_id'), table_name='collaborators')
    op.create_index(op.f('ix_collaborators_collab_id'), 'collaborators', ['collab_id'], unique=True)
    op.drop_column('collaborators', 'profile_url')
    # ### end Alembic commands ###
