""" ADD Flags for fullstack, frontend & backend.

Revision ID: 79b55ab3ed7f
Revises: 
Create Date: 2026-03-17 09:21:30.719872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b55ab3ed7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_backend', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('repositories', sa.Column('is_frontend', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('repositories', sa.Column('is_fullstack', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('repositories', sa.Column('is_collaborator', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_collaborator')
    op.drop_column('repositories', 'is_fullstack')
    op.drop_column('repositories', 'is_frontend')
    op.drop_column('repositories', 'is_backend')
    # ### end Alembic commands ###
