"""Add CollaboratorModel

Revision ID: 870ae6609935
Revises: 5938e92cbce1
Create Date: 2026-05-18 15:31:34.743457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870ae6609935'
down_revision: Union[str, Sequence[str], None] = '5938e92cbce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('collab_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborators_collab_id'), 'collaborators', ['collab_id'], unique=True)
    op.create_index(op.f('ix_collaborators_id'), 'collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_collaborators_name'), 'collaborators', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborators_name'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_collab_id'), table_name='collaborators')
    op.drop_table('collaborators')
    # ### end Alembic commands ###
