"""add is_fork and parent_owner to RepositoryModel

Revision ID: 98ae5227b9f9
Revises: 42ef1404e378
Create Date: 2026-06-02 17:03:42.366740

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98ae5227b9f9"
down_revision: str | Sequence[str] | None = "42ef1404e378"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("is_fork", sa.Boolean(), nullable=True))
    op.execute("UPDATE repositories SET is_fork = false")
    op.alter_column("repositories", "is_fork", nullable=False)
    op.add_column("repositories", sa.Column("parent_owner", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "parent_owner")
    op.drop_column("repositories", "is_fork")
    # ### end Alembic commands ###
