"""rename_association_tables

Revision ID: a77ab3d7fe6c
Revises: 16b1122def47
Create Date: 2026-05-19 08:04:13.354363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77ab3d7fe6c'
down_revision: Union[str, Sequence[str], None] = '16b1122def47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration_assosiation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('collab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['collaborators.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_assosiation_id'), 'collaboration_assosiation', ['id'], unique=False)
    op.create_table('language_assosiation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('code_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_assosiation_id'), 'language_assosiation', ['id'], unique=False)
    op.drop_index(op.f('ix_language_repository_association_id'), table_name='language_repository_association')
    op.drop_table('language_repository_association')
    op.drop_index(op.f('ix_repo_collaborator_association_id'), table_name='repo_collaborator_association')
    op.drop_table('repo_collaborator_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_collaborator_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('collab_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['collaborators.id'], name=op.f('repo_collaborator_association_collab_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], name=op.f('repo_collaborator_association_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('repo_collaborator_association_pkey'))
    )
    op.create_index(op.f('ix_repo_collaborator_association_id'), 'repo_collaborator_association', ['id'], unique=False)
    op.create_table('language_repository_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lang_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('code_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['languages.id'], name=op.f('language_repository_association_lang_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], name=op.f('language_repository_association_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('language_repository_association_pkey'))
    )
    op.create_index(op.f('ix_language_repository_association_id'), 'language_repository_association', ['id'], unique=False)
    op.drop_index(op.f('ix_language_assosiation_id'), table_name='language_assosiation')
    op.drop_table('language_assosiation')
    op.drop_index(op.f('ix_collaboration_assosiation_id'), table_name='collaboration_assosiation')
    op.drop_table('collaboration_assosiation')
    # ### end Alembic commands ###
