"""add_composite_unique_constraint_to_collaborators

Revision ID: aa01d048ea25
Revises: 6e62a9dc8243
Create Date: 2026-05-19 07:35:16.503782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa01d048ea25'
down_revision: Union[str, Sequence[str], None] = '6e62a9dc8243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_repo_collaborator_uc', 'collaborators', ['repo_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_repo_collaborator_uc', 'collaborators', type_='unique')
    # ### end Alembic commands ###
