"""remove is_fork from RepositoryModel

Revision ID: bdb0bc14aa04
Revises: 98ae5227b9f9
Create Date: 2026-06-03 09:11:30.437652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb0bc14aa04'
down_revision: Union[str, Sequence[str], None] = '98ae5227b9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('contribution_ratio', sa.Integer(), nullable=True))
    op.execute("UPDATE repositories SET contribution_ratio = 100")
    op.alter_column('repositories', 'contribution_ratio', nullable=False)
    op.drop_column('repositories', 'is_fork')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_fork', sa.BOOLEAN(), server_default='false', nullable=False))
    op.drop_column('repositories', 'contribution_ratio')
    # ### end Alembic commands ###
