name: Semantic Release

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --package=semantic-release \
              --package=@semantic-release/changelog \
              --package=@semantic-release/git \
              --package=@semantic-release/npm \
              semantic-release