name: Application Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_call:

jobs:
  test-frontend:
    name: Run Unit Tests (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Tests
        run: |
          cd frontend
          npm run test
